# Generated by Django 3.0.7 on 2020-06-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.IntegerField(default=0)),
                ('post', models.IntegerField(default=0)),
                ('people_exist', models.IntegerField(blank=True, default=0, null=True)),
                ('sound', models.IntegerField(blank=True, default=0, null=True)),
                ('musical', models.IntegerField(blank=True, default=0, null=True)),
                ('grayscale', models.IntegerField(blank=True, default=0, null=True)),
                ('experience', models.IntegerField(blank=True, default=0, null=True)),
                ('lucidity', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=1000000, null=True)),
                ('interpretation', models.CharField(blank=True, max_length=1000000, null=True)),
                ('day', models.IntegerField(blank=True, default=0, null=True)),
                ('month', models.IntegerField(blank=True, default=0, null=True)),
                ('year', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.IntegerField(default=0)),
                ('post', models.IntegerField(default=0)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('second_name', models.CharField(blank=True, max_length=255)),
                ('third_name', models.CharField(blank=True, max_length=255)),
                ('fourth_name', models.CharField(blank=True, max_length=255)),
                ('fifth_name', models.CharField(blank=True, max_length=255)),
                ('sixth_name', models.CharField(blank=True, max_length=255)),
                ('seventh_name', models.CharField(blank=True, max_length=255)),
                ('eighth_name', models.CharField(blank=True, max_length=255)),
                ('ninth_name', models.CharField(blank=True, max_length=255)),
                ('tenth_name', models.CharField(blank=True, max_length=255)),
                ('first_impression', models.IntegerField(blank=True, default=0)),
                ('second_impression', models.IntegerField(blank=True, default=0)),
                ('third_impression', models.IntegerField(blank=True, default=0)),
                ('fourth_impression', models.IntegerField(blank=True, default=0)),
                ('fifth_impression', models.IntegerField(blank=True, default=0)),
                ('sixth_impression', models.IntegerField(blank=True, default=0)),
                ('seventh_impression', models.IntegerField(blank=True, default=0)),
                ('eighth_impression', models.IntegerField(blank=True, default=0)),
                ('ninth_impression', models.IntegerField(blank=True, default=0)),
                ('tenth_impression', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.IntegerField(default=0)),
                ('post', models.IntegerField(default=0)),
                ('q1', models.IntegerField(blank=True, default=0)),
                ('q2', models.IntegerField(blank=True, default=0)),
                ('q3', models.IntegerField(blank=True, default=0)),
                ('q4', models.IntegerField(blank=True, default=0)),
                ('q5', models.IntegerField(blank=True, default=0)),
                ('q6', models.IntegerField(blank=True, default=0)),
                ('q7', models.IntegerField(blank=True, default=0)),
                ('q8', models.IntegerField(blank=True, default=0)),
                ('q9', models.IntegerField(blank=True, default=0)),
                ('q10', models.IntegerField(blank=True, default=0)),
                ('q11', models.IntegerField(blank=True, default=0)),
                ('q12', models.IntegerField(blank=True, default=0)),
                ('q13', models.IntegerField(blank=True, default=0)),
                ('q14', models.IntegerField(blank=True, default=0)),
                ('q15', models.IntegerField(blank=True, default=0)),
                ('q16', models.IntegerField(blank=True, default=0)),
                ('q17', models.IntegerField(blank=True, default=0)),
                ('q18', models.IntegerField(blank=True, default=0)),
                ('q19', models.IntegerField(blank=True, default=0)),
                ('result', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField(default=0)),
                ('user_no', models.IntegerField(default=0)),
                ('time', models.IntegerField(blank=True, default=0)),
                ('physical_activity', models.IntegerField(blank=True, default=0)),
                ('food_consumption', models.IntegerField(blank=True, default=0)),
                ('dream_remembered', models.IntegerField(blank=True, default=0)),
                ('day', models.IntegerField(blank=True, default=0)),
                ('month', models.IntegerField(blank=True, default=0)),
                ('year', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
